name: Build CI [Windows ARM64]

on:
  push:
    paths:
      - .github/workflows/build_ci_windows_arm.yml
      - assets/**
      - examples/**
      - include/**
      - installer/**
      - lib/**
      - src/**
      - std/**
      - test/**
      - tools/**
      - build.py
    branches:
      - main

jobs:
  build:
    runs-on: windows-11-arm
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2 for ARM64
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: >-
            base
            brotli
            bsdtar
            bzip2
            ca-certificates
            coreutils
            curl
            dash
            db
            gawk
            gcc-libs
            getent
            gettext
            git
            gmp
            gnupg
            gzip
            heimdal
            heimdal-libs
            inetutils
            libargp
            libasprintf
            libassuan
            libbz2
            libcbor
            libcurl
            libdb
            libedit
            libexpat
            libffi
            libfido2
            libgcrypt
            libgdbm
            libgettextpo
            libgnutls
            libgpg-error
            libhogweed
            libiconv
            libidn2
            libintl
            libksba
            liblz4
            liblzma
            libnettle
            libnghttp2
            libnpth
            libopenssl
            libp11-kit
            libpcre
            libpcre2_8
            libpsl
            libreadline
            libsqlite
            libssh2
            libtasn1
            libunistring
            libutil-linux
            libxcrypt
            libzstd
            lzip
            mingw-w64-clang-aarch64-7zip
            mingw-w64-clang-aarch64-adwaita-icon-theme
            mingw-w64-clang-aarch64-adwaita-icon-theme-legacy
            mingw-w64-clang-aarch64-atk
            mingw-w64-clang-aarch64-atkmm
            mingw-w64-clang-aarch64-binutils
            mingw-w64-clang-aarch64-brotli
            mingw-w64-clang-aarch64-bzip2
            mingw-w64-clang-aarch64-c-ares
            mingw-w64-clang-aarch64-ca-certificates
            mingw-w64-clang-aarch64-cairo
            mingw-w64-clang-aarch64-cairomm
            mingw-w64-clang-aarch64-crt-git
            mingw-w64-clang-aarch64-curl
            mingw-w64-clang-aarch64-dbus
            mingw-w64-clang-aarch64-double-conversion
            mingw-w64-clang-aarch64-egl-headers
            mingw-w64-clang-aarch64-expat
            mingw-w64-clang-aarch64-fontconfig
            mingw-w64-clang-aarch64-freetype
            mingw-w64-clang-aarch64-fribidi
            mingw-w64-clang-aarch64-gcc
            mingw-w64-clang-aarch64-gcc-libs
            mingw-w64-clang-aarch64-gdk-pixbuf2
            mingw-w64-clang-aarch64-gettext-libtextstyle
            mingw-w64-clang-aarch64-gettext-runtime
            mingw-w64-clang-aarch64-gettext-tools
            mingw-w64-clang-aarch64-giflib
            mingw-w64-clang-aarch64-gles-headers
            mingw-w64-clang-aarch64-glew
            mingw-w64-clang-aarch64-glfw
            mingw-w64-clang-aarch64-glib2
            mingw-w64-clang-aarch64-glibmm
            mingw-w64-clang-aarch64-gmp
            mingw-w64-clang-aarch64-gnutls
            mingw-w64-clang-aarch64-graphite2
            mingw-w64-clang-aarch64-gtk-update-icon-cache
            mingw-w64-clang-aarch64-gtk3
            mingw-w64-clang-aarch64-gtkmm
            mingw-w64-clang-aarch64-gtkmm3
            mingw-w64-clang-aarch64-gumbo-parser
            mingw-w64-clang-aarch64-harfbuzz
            mingw-w64-clang-aarch64-headers-git
            mingw-w64-clang-aarch64-hicolor-icon-theme
            mingw-w64-clang-aarch64-hidapi
            mingw-w64-clang-aarch64-icu
            mingw-w64-clang-aarch64-isl
            mingw-w64-clang-aarch64-jbigkit
            mingw-w64-clang-aarch64-json-glib
            mingw-w64-clang-aarch64-lerc
            mingw-w64-clang-aarch64-libb2
            mingw-w64-clang-aarch64-libdatrie
            mingw-w64-clang-aarch64-libdeflate
            mingw-w64-clang-aarch64-libepoxy
            mingw-w64-clang-aarch64-libffi
            mingw-w64-clang-aarch64-libiconv
            mingw-w64-clang-aarch64-libidn2
            mingw-w64-clang-aarch64-libjpeg-turbo
            mingw-w64-clang-aarch64-libmangle-git
            mingw-w64-clang-aarch64-libpng
            mingw-w64-clang-aarch64-libpsl
            mingw-w64-clang-aarch64-librsvg
            mingw-w64-clang-aarch64-libsigc++
            mingw-w64-clang-aarch64-libssh2
            mingw-w64-clang-aarch64-libsystre
            mingw-w64-clang-aarch64-libtasn1
            mingw-w64-clang-aarch64-libthai
            mingw-w64-clang-aarch64-libtiff
            mingw-w64-clang-aarch64-libtre
            mingw-w64-clang-aarch64-libunistring
            mingw-w64-clang-aarch64-libwebp
            mingw-w64-clang-aarch64-libwinpthread-git
            mingw-w64-clang-aarch64-libxml2
            mingw-w64-clang-aarch64-libzip
            mingw-w64-clang-aarch64-litehtml
            mingw-w64-clang-aarch64-lzo2
            mingw-w64-clang-aarch64-make
            mingw-w64-clang-aarch64-md4c
            mingw-w64-clang-aarch64-mpc
            mingw-w64-clang-aarch64-mpdecimal
            mingw-w64-clang-aarch64-mpfr
            mingw-w64-clang-aarch64-ncurses
            mingw-w64-clang-aarch64-nettle
            mingw-w64-clang-aarch64-nghttp2
            mingw-w64-clang-aarch64-nghttp3
            mingw-w64-clang-aarch64-ngtcp2
            mingw-w64-clang-aarch64-ntldd
            mingw-w64-clang-aarch64-openmp
            mingw-w64-clang-aarch64-openssl
            mingw-w64-clang-aarch64-p11-kit
            mingw-w64-clang-aarch64-pango
            mingw-w64-clang-aarch64-pangomm
            mingw-w64-clang-aarch64-pcre2
            mingw-w64-clang-aarch64-pdcurses
            mingw-w64-clang-aarch64-pixman
            mingw-w64-clang-aarch64-pkg-config
            mingw-w64-clang-aarch64-python
            mingw-w64-clang-aarch64-python-packaging
            mingw-w64-clang-aarch64-python-py-cpuinfo
            mingw-w64-clang-aarch64-qt-creator
            mingw-w64-clang-aarch64-qt5-base
            mingw-w64-clang-aarch64-qt6-5compat
            mingw-w64-clang-aarch64-qt6-base
            mingw-w64-clang-aarch64-qt6-declarative
            mingw-w64-clang-aarch64-qt6-quick3d
            mingw-w64-clang-aarch64-qt6-serialport
            mingw-w64-clang-aarch64-qt6-shadertools
            mingw-w64-clang-aarch64-qt6-svg
            mingw-w64-clang-aarch64-qt6-tools
            mingw-w64-clang-aarch64-qt6-translations
            mingw-w64-clang-aarch64-readline
            mingw-w64-clang-aarch64-shared-mime-info
            mingw-w64-clang-aarch64-sqlite3
            mingw-w64-clang-aarch64-tcl
            mingw-w64-clang-aarch64-termcap
            mingw-w64-clang-aarch64-tk
            mingw-w64-clang-aarch64-toolchain
            mingw-w64-clang-aarch64-tools-git
            mingw-w64-clang-aarch64-tzdata
            mingw-w64-clang-aarch64-vulkan-headers
            mingw-w64-clang-aarch64-vulkan-loader
            mingw-w64-clang-aarch64-windows-default-manifest
            mingw-w64-clang-aarch64-wineditline
            mingw-w64-clang-aarch64-winpthreads-git
            mingw-w64-clang-aarch64-winstorecompat-git
            mingw-w64-clang-aarch64-xxhash
            mingw-w64-clang-aarch64-xz
            mingw-w64-clang-aarch64-yaml-cpp
            mingw-w64-clang-aarch64-zlib
            mingw-w64-clang-aarch64-zstd
            ncurses
            nettle
            openssh
            openssl
            xz
            zip
            zlib
            zstd

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: arm64

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.300'

      - name: Install WiX Toolset v4
        shell: pwsh
        run: dotnet tool install --global wix

      - name: Checkout code
        run:
          git clone https://github.com/rhea-language/rhea

      - name: Build Rhea
        run: |
          cd rhea
          pwd
          where g++
          python build.py

      - name: Build WiX project
        shell: pwsh
        run: |
          cd rhea\installer\RheaWindowsInstaller
          nuget restore RheaWindowsInstaller.sln
          msbuild RheaWindowsInstaller.sln /p:Configuration=Release
          mv bin\ARM64\Release\en-US\RheaWindowsInstaller.msi ..\..\dist\rhea-win-arm64-1.0.0.msi

      - name: Set Environment Path
        shell: bash
        run: |
          cd rhea
          echo "RHEA_PATH=$PWD/dist/rhea-lang" >> $GITHUB_ENV

      - name: Build verification
        shell: bash
        run: |
          cd rhea
          ./dist/rhea-lang/bin/rhea
          ls -R dist

      - name: Zip the Built Files
        shell: pwsh
        run: |
          cd rhea
          Compress-Archive -Path .\dist\rhea-lang -DestinationPath .\dist\rhea-win-arm64-1.0.0.zip
          Remove-Item -Path .\dist\rhea-lang -Recurse -Force

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: rhea-windows-arm64
          path: rhea/dist
          retention-days: 1
